spring:
  application:
    name: icemgr-rest
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8080

dubbo:
  registry:
    address: nacos://localhost:8848
    check: true
    group: dubbo-dev
  scan:
    base-packages: com.hzqing.rest
debug: true
