spring:
  application:
    name: icemgr-rest
  mvc:
    throw-exception-if-no-handler-found: true # 出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
server:
  port: 8090
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    port: -1
  consumer:
    validation: true
debug: true
